### ISSUE TITLE
Memory Leak and Fatal Errors

### ISSUE THREAD

**Issue by RyanMulready** [maranran/eslint-plugin-vue-a11y#1]
With just the base config turned on I am getting this in my ESLint log

`(node:15045) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
(node:15045) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
(node:15045) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit`

With the recommended config turned on ESLint won't even run and returns this in the log

`The expression evaluated to a falsy value:
  assert(node && node.type === 'VElement')
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  assert(node && node.type === 'VElement')
   at Object.hasAttribute (/node_modules/eslint-plugin-vue/lib/utils/index.js:86:5)
`

**Comment by maranran** [comment]
thanks for your issue, I have tried to fixed it, you can update the version to see it @RyanMulready

**Comment by RyanMulready** [comment]
base now works well, thank you.  Recommended still has the memory leak warning.

**Comment by cj** [comment]
@maranran I'm still getting this error.

**Comment by charliethomason** [comment]
I am also still getting this error. This issue should not be closed as it is still happening.
