### ISSUE TITLE
vue-a11y/label-has-for

### ISSUE THREAD

**Issue by RyanMulready** [maranran/eslint-plugin-vue-a11y#2]
This rule is currently broken, using the attribute for="idOfElement" or htmlFor="idOfElement" both do not work correctly and an error is always thrown.

**Comment by maranran** [comment]
It may be because this rule's option defaults to "required": { "every": ["nesting", "id"] } (In order to keep correspondence with https://github.com/evcohen/eslint-plugin-jsx-a11y)   it means you should nesting input and has id for it , You can solve it like this way:
 "rules": {
        "jsx-a11y/label-has-for": [ 2, {
            "components": [ "Label" ],
            "required": {
                "some": [ "nesting", "id" ]
            },
            "allowChildren": false
        }]
    }

**Comment by maranran** [comment]
@RyanMulready  It may be because this rule's option defaults to "required": { "every": ["nesting", "id"] } (In order to keep correspondence with https://github.com/evcohen/eslint-plugin-jsx-a11y) it means you should nesting input and has id for it , You can solve it like this way:
```
{
    "rules": {
        "jsx-a11y/label-has-for": [ 2, {
            "components": [ "Label" ],
            "required": {
                "every": [ "nesting", "id" ]
            },
            "allowChildren": false
        }]
    }
}
```

**Comment by maranran** [comment]
@RyanMulready  It may be because this rule's option defaults to "required": { "every": ["nesting", "id"] } (In order to keep correspondence with https://github.com/evcohen/eslint-plugin-jsx-a11y) it means you should nesting input and has id for it , You can solve it like this way:

{
    "rules": {
        "jsx-a11y/label-has-for": [ 2, {
            "components": [ "Label" ],
            "required": {
                "some": [ "nesting", "id" ]
            },
            "allowChildren": false
        }]
    }
}
