### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by manniL** [maranran/eslint-plugin-vue-a11y#7]
Heya!

The warnings from #1 are still present.

**Comment by seancrater** [comment]
Bump, this is still an issue

**Comment by sawa-zen** [comment]
I am fixing this problem
https://github.com/mysticatea/vue-eslint-parser/pull/44

**Comment by charliethomason** [comment]
I am still seeing this problem in v0.0.31

**Comment by sawa-zen** [comment]
@charliethomason 
It is because `eslint-plugin-vue` used by `vue-eslint-parser` is old.
I am also creating a PR for this.
https://github.com/vuejs/eslint-plugin-vue/pull/895
